module Attributes
  ATTRIBUTES = ["strength", "dexterity", "vitality", "energy"]
  CLASSES = ["amazon", "assassin", "barbarian", "druid", "necromancer", "paladin", "sorceress"]
  ELEMENTS = ["lightning", "fire", "poison", "cold"]
  DAMAGES = ["lightning", "fire", "poison", "cold", "magic", "physical"]
	
  SKILLS = [
    "amplify damage",
    "armageddon",
    "battle command",
    "blessed hammer",
    "blizzard",
    "blood golem",
    "bone armor",
    "bone spear",
    "bone spirit",
    "burst of speed",
    "carrion vine",
    "chain lightning",
    "charged bolt",
    "clay golem",
    "cloak of shadows",
    "confuse",
    "conviction",
    "corpse explosion",
    "critical strike",
    "cyclone armor",
    "decrepify",
    "dodge",
    "double throw",
    "energy shield",
    "fire ball",
    "fire bolt",
    "fire golem",
    "fire mastery",
    "fire wall",
    "fissure",
    "frenzy",
    "frost nova",
    "frozen armor",
    "frozen orb",
    "glacial spike",
    "grim ward",
    "guided arrow",
    "heart of wolverine",
    "holy bolt",
    "holy shock",
    "howl",
    "hydra",
    "inferno",
    "iron golem",
    "iron maiden",
    "leap",
    "lightning",
    "lycanthropy",
    "meteor",
    "mind blast",
    "multiple shot",
    "nova",
    "oak sage",
    "poison creeper",
    "poison explosion",
    "poison nova",
    "raise skeletal mage",
    "raise skeleton",
    "raven",
    "revive",
    "sanctuary",
    "shadow master",
    "shock wave",
    "shout",
    "skeleton mastery",
    "slow missiles",
    "spirit of barbs",
    "static field",
    "strafe",
    "summon dire wolf",
    "summon grizzly",
    "summon spirit wolf",
    "twister",
    "valkyrie",
    "warmth",
    "weaken",
    "werebear",
    "werewolf"
	]  
  
  STATS = [
    "[x] chance to cast level [y] [skill] on striking",
    "[x] chance to cast level [y] [skill] when struck",
    "level [x] [skill] ([y] charges)",
    "indestructible",
    "[x] to all skills",
    "[x] to [class] skill levels",
    "[x] to cold skills ([class] only)",
    "[x] to bow and crossbow skills ([class] only)",
    "[x] to fire skills",
    "[x] to poison and bone skills ([class] only)",
    "[x] increased attack speed",
    "[x] faster cast rate",
    "[x] faster block rate",
    "[x] faster hit recovery",
    "[x] faster run/walk",
    "[x] increased chance of blocking",
    "fires explosive arrows or bolts",
    "piercing attack",
    "[x] to minimum damage",
    "[x] to maximum damage",
    "[x] to maximum damage per character level",
    "[x] enhanced maximum damage per character level",
    "[x] enhanced damage",
    "[x] kick damage",
    "adds [x] damage",
    "adds [x] magic damage",
    "adds [x] [element] damage",
    "[x] [element] damage over [y] seconds",
    "[x] bonus to attack rating",
    "[x] to attack rating",
    "[x] to attack rating per character level",
    "[x] to attack rating to undead",
    "[x] to attack rating against demons",
    "[x] to attack rating against undead",
    "[x] deadly strike",
    "[x] chance of crushing blow",
    "[x] chance of open wounds",
    "[x] life stolen per hit",
    "[x] mana stolen per hit",
    "hit causes monster to flee [x]",
    "slows target by [x]",
    "[x] target defense",
    "ignore target's defense",
    "hit blinds target",
    "hit blinds target [x]",
    "freezes target",
    "freezes target [x]",
    "prevent monster heal",
    "knockback",
    "[x] defense vs missile",
    "[x] monster defense per hit",
    "[x] to monster defense per hit",
    "[x] to life",
    "[x] to life per character level",
    "replenish life [x]",
    "increase maximum life [x]",
    "drain life [x]",
    "[x] to mana",
    "[x] to mana per character level",
    "regenerate mana [x]",
    "increase maximum mana [x]",
    "[x] maximum stamina",
    "heal stamina [x]",
    "[x] slower stamina drain",
    "[x] defense",
    "[x] defense per character level",
    "[x] enhanced defense",
    "[x] to [attribute]",
    "[x] to [attribute] per character level",
    "[x] to life after each demon kill",
    "[x] to life after each kill",
    "[x] to mana after each kill",    
    "[x] to maximum [element] resist",
    "[element] resist [x]",
    "magic resist [x]",
    "all resistances [x]",
    "damage reduced by [x]",
    "magic damage reduced by [x]",
    "poison length reduced by [x]",
    "[x] damage taken goes to mana",
    "[x] to light radius",
    "increase maximum durability [x]",
    "attacker takes [element] damage of [x]",
    "attacker takes damage of [x]",
    "half freeze duration",
    "cannot be frozen",
    "[x] better chance of getting magic items",
    "[x] better chance of getting magic items per character level",
    "[x] extra gold from monsters",
    "[x] extra gold from monsters per character level",
    "repairs [x] durability in [y] seconds",
    "[x] damage to demons",
    "[x] damage to demons per character level",
    "[x] damage to undead",
    "requirements [x]",
    "[x] to [skill] ([class] only)"
  ]
end
