module ItemTypes
  MASTER_TYPES = {
      "Armors" => ["Any armor", "Belt", "Boots", "Circlet", "Gloves", "Helmet", "Shield", "Torso armor"],
      "Weapons" => ["Any weapon", "Any melee weapon", "Any missile weapon", "Axe", "Blunt weapon", "Bow", "Club",
                    "Crossbow", "Hammer", "Javelin", "Knife", "Mace", "Polearm", "Rod (Scepter, Staff, Wand)",
                    "Scepter", "Staff", "Wand", "Spear", "Sword", "Thrown weapon", "Thrown axe", "Thrown knife"],
      "Class items" => ["Amazon bow", "Amazon javelin", "Amazon spear", "Auric shield", "Claw", "Druid pelt",
                        "Necro head", "Orb", "Primal helmet"],
      "Charms" => ["Any charm", "Charm: Hex", "Charm: Large", "Charm: Narrow", "Charm: Quad", "Charm: Tall"]
    }

  TYPES = {
    "Show All Items" => [:all],
    "Any armor" => [:ar, :be, :bt, :ci, :gl, :he, :to],
    "Belt" => [:be, :ar],
    "Boots" => [:bt, :ar],
    "Circlet" => [:ci, :he, :ar],
    "Gloves" => [:gl, :ar],
    "Helmet" => [:he, :ar],
    "Shield" => [:sh, :ar],
    "Torso armor" => [:to, :ar],
    "Any weapon" => [:we, :me, :mi, :ax, :bl, :cb, :bo, :ha, :kn, :ja, :ma, :po, :ro, :sc, :st, :sw, :sp, :th, :ta, :tk, :xb],
    "Any melee weapon" => [:me, :we, :ax, :bl, :cb, :ha, :kn, :ja, :ma, :po, :ro, :sc, :st, :sw, :sp, :th, :ta, :tk],
    "Any missile weapon" => [:mi, :we, :bo, :xb, :ab],
    "Axe" => [:ax, :me, :we],
    "Blunt weapon" => [:bl, :me, :we],
    "Bow" => [:bo, :mi, :we],
    "Club" => [:cb, :me, :we],
    "Crossbow" => [:xb, :mi, :we],
    "Hammer" => [:ha, :me, :we],
    "Javelin" => [:ja, :th, :me, :we],
    "Knife" => [:kn, :me, :we],
    "Mace" => [:ma, :me, :we],
    "Polearm" => [:po, :me, :we],
    "Rod (Scepter, Staff, Wand)" => [:ro, :me, :we],
    "Scepter" => [:sc, :ro, :me, :we],
    "Staff" => [:st, :ro, :me, :we],
    "Wand" => [:wa, :ro, :me, :we],
    "Spear" => [:sp, :me, :we],
    "Sword" => [:sw, :me, :we],
    "Thrown weapon" => [:th, :me, :we, :ta, :tk, :ja, :aj],
    "Thrown axe" => [:ta, :th, :me, :we],
    "Thrown knife" => [:tk, :th, :me, :we],
    "Amazon bow" => [:ab, :bo, :mi, :we],
    "Amazon javelin" => [:aj, :ja, :th, :me, :we],
    "Amazon spear" => [:as, :sp, :me, :we],
    "Auric shield" => [:au, :sh, :ar],
    "Claw" => [:cw, :me, :we],
    "Druid pelt" => [:pe, :he, :ar],
    "Necro head" => [:hd, :sh, :ar],
    "Orb" => [:or, :me, :we],
    "Primal helmet" => [:ph, :he, :ar],
    "Any charm" => [:cm, :ch, :cl, :cq, :ct, :cn],
    "Charm: Hex" => [:ch, :cm],
    "Charm: Large" => [:cl, :cm],
    "Charm: Narrow" => [:cn, :cm],
    "Charm: Quad" => [:cq, :cm],
    "Charm: Tall" => [:ct, :cm]
  }
end